# credentials.py

# Kik credentials
KIK_USERNAME = 'YOUR_KIK_USERNAME'
KIK_API_KEY = 'YOUR_KIK_API_KEY'

# Telegram credentials
TELEGRAM_TOKEN = 'YOUR_TELEGRAM_TOKEN'

# Instagram credentials
INSTAGRAM_USERNAME = 'YOUR_INSTAGRAM_USERNAME'
INSTAGRAM_PASSWORD = 'YOUR_INSTAGRAM_PASSWORD'

# Messenger credentials
MESSENGER_PAGE_ACCESS_TOKEN = 'YOUR_PAGE_ACCESS_TOKEN'
MESSENGER_APP_SECRET = 'YOUR_APP_SECRET'
MESSENGER_VERIFICATION_TOKEN = 'YOUR_VERIFICATION_TOKEN'

# OnlyFans Affiliate API credentials
ONLYFANS_USERNAME = 'YOUR_ONLYFANS_USERNAME'
ONLYFANS_API_KEY = 'YOUR_ONLYFANS_API_KEY'